server:
  port: 9527
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://www.baidu.com  #lb://product-server
          predicates:
          - Path=/product/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
      registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1

